### ISSUE TITLE
Error when running search from command line

### ISSUE THREAD

**Issue by przemekff** [DeepWok/mase#45]
Commit hash: 6a7f1cd

Trying to run the search space from command line as indicated in the in lab 3 doc

Had to add  `--load-type pl` as the default option is `mz`

`!./ch search --config configs/examples/jsc_toy_by_type.toml --load-type pl --load "/content/drive/MyDrive/mase_outputs/batch_size_256/software/training_ckpts/best.ckpt"`

```
INFO     Initialising model 'jsc-tiny'...\
INFO     Initialising dataset 'jsc'...\
INFO     Project will be created at /content/mase/mase_output/jsc-tiny\
INFO     Loaded pytorch lightning checkpoint from /content/drive/MyDrive/mase_outputs/batch_size_128/software/training_ckpts/best.ckpt
INFO     Loaded model from /content/drive/MyDrive/mase_outputs/batch_size_128/software/training_ckpts/best.ckpt.
INFO     Building search space...
INFO     Search started...
100% 20/20 [00:03<00:00,  6.26it/s, 3.19/20000 seconds]
Traceback (most recent call last):
  File "/content/mase/machop/./ch", line 6, in <module>
    ChopCLI().run()
  File "/content/mase/machop/chop/cli.py", line 270, in run
    run_action_fn()
  File "/content/mase/machop/chop/cli.py", line 395, in _run_search
    search(**search_params)
  File "/content/mase/machop/chop/actions/search/search.py", line 92, in search
    strategy.search(search_space)
  File "/content/mase/machop/chop/actions/search/strategies/optuna.py", line 153, in search
    self._save_best(study, self.save_dir / "best.json")
  File "/content/mase/machop/chop/actions/search/strategies/optuna.py", line 234, in _save_best
    ].map(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'map'. Did you mean: 'mad'?`

```

**Comment by Aaron-Zhao123** [comment]
See here https://github.com/DeepWok/mase/issues/37, https://github.com/DeepWok/mase/issues/37#issuecomment-1919191598
